name: ARM64 CI WorkFlow
on:
  push: null
env:
  CONTAINER_RUN_OPTIONS: ' '
  GINKGO_VERSION: v2.17.1
jobs:
  image-prepare:
    runs-on: openeuler-linux-arm64
    steps:
    - name: Pull kubeedge/build-tools image
      run: 'docker pull kubeedge/build-tools:1.22.9-ke1

        mkdir -p /home/runner/build-tools/

        docker save kubeedge/build-tools:1.22.9-ke1 > /home/runner/build-tools/build-tools.tar

        '
    - name: Clear previous content
      run: sudo rm -rf /home/runner/actions-runner/_work/kubeedge/kubeedge/*
    - uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: docker load kubeedge/build-tools image
      run: docker load < /home/runner/build-tools/build-tools.tar
    - run: make
    - run: make smallbuild
